-- Script generated by SimpleSpy - credits to exx#9394

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local player = Players.LocalPlayer
local boostFolder = player:FindFirstChild("Boost")

if boostFolder then
	for _, v in ipairs(boostFolder:GetChildren()) do
		if v:IsA("BoolValue") and v.Name == "2xEarn" then
			-- Solo borrar si NO tiene el atributo CreatedByScript
			if v:GetAttribute("CreatedByScript") == nil then
				v:Destroy()
				break -- Solo borra 1 por ejecución
			end
		end
	end
end

task.wait(0.2)

local args = {
	[1] = "2xEarn"
}

ReplicatedStorage.UseBoost:FireServer(unpack(args))
